### PR TITLE
Fix single host tomcat classloader exception

### PR DESCRIPTION
**Pull request by wuqian0808**
When using single host mode and running in IDE, the arkautoconfiguration in other embemed ark biz model will not match @ConditionalOnClass(name="xxx.ArkTomcatEmbeddedWebappClassLoader") condition, cause this class can not be detected by the embemed ark model. Export this pkg in web-plugin or modify the ark-maven-plugin to package the web-plugin can fix this issue.

### CODE REVIEW

**Comment by lvjing2** [comment]
what's your startup parameters, I can't reproduce your problem. each biz classLoader should add the plugins' url into it's ucp by this method.
image

so each biz can find this class.

**Comment by wuqian0808** [comment]
> what's your startup parameters, please tell more about your problem. and please know that each biz classLoader would add the plugins' url into it's ucp by this method. image
> 
> so each biz can find this class. so your PR may not need, please check this.


bring up the host app by idea with command -Dcom.alipay.sofa.ark.master.biz="Startup In IDE". Other biz app is imported by maven with classifier ark-biz.

This issue is because the plugin is registered later than biz. So when create bizclassloader, the plugin may not be registed and detected.

Maybe it's better to adjust plugin register oder earlier than biz?

**Comment by lvjing2** [comment]
yes, as we describe in the [demo](https://github.com/sofastack-guides/sofa-ark-dynamic-guides), we all register the plugin before bizs.

**Comment by lvjing2** [comment]
Did this problem still here? I think it should not be a problem if you add web-ark-plugin dependency in the ArkBase or master biz.

**Review by lvjing2 — APPROVED** [review]
LGTM

**Comment by lvjing2** [comment]
same as #737

**Pull request merged**
