### PR TITLE
feat: support soft link java agent

### PR DESCRIPTION
**Pull request by xingcici**
### Motivation:

Some company use soft link to load java agent.
The previous way to get java agent path can not get real path，but classloader get real path，so ark can not filter and load success.

### Modification:

get real path.

### CODE REVIEW

**Comment by lvjing2** [comment]
This's true, SOFAArk may not support such case very well, I am wondering is there any more needed to be fixed, can you check this?
And please don't forget sign the CLA.

**Comment by xingcici** [comment]
> This's true, SOFAArk may not support such case very well, I am wondering is there any more needed to be fixed, can you check this? And please don't forget sign the CLA.

I'd like to sign the cla, but the cla sever is not stable. It's always redirect to the base page or when i click submit but there is no response until timeout.
image

**Comment by xingcici** [comment]
> > This's true, SOFAArk may not support such case very well, I am wondering is there any more needed to be fixed, can you check this? And please don't forget sign the CLA.
> 

sure, I'd like to. I will check it when i get free.

**Review by lvjing2 — APPROVED** [review]
LGTM

**Pull request merged**
