### PR TITLE
Supplement the return type and repair the code style

### PR DESCRIPTION
**Pull request by azhsmesos**
Optimize the code style to prevent @suppresswarnings related comments from appearing as little as possible.
assigned issue：https://github.com/sofastack/sofa-ark/issues/516

### CODE REVIEW

**Review by glmapper — APPROVED** [review]
LGTM

**Comment by azhsmesos** [comment]
> LGTM

Hello, I don't understand what LGTM means.

**Comment by glmapper** [comment]
@azhsmesos check your test cases

**Comment by azhsmesos** [comment]
> @azhsmesos check your test cases
我去看下为啥报错，因为我并没有更改test case

**Pull request merged**
