### PR TITLE
fix null package issue - Instead of original pr "Fix null pacakge"

### PR DESCRIPTION
**Pull request by wuqian0808**
Fix demo start up without loading biz lib

### CODE REVIEW

**Comment by wuqian0808** [comment]
@lvjing2 Use this pr instead of the original ones

**Comment by wuqian0808** [comment]
> @lvjing2 Use this pr instead of the original ones

The check_format.sh is running well with this pr.

**Comment by lvjing2** [comment]
Still need to execute this shell command, you will see the diff after executing.
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -U && sh ./check_format.sh`

**Comment by wuqian0808** [comment]
> Still need to execute this shell command, you will see the diff after executing. `mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -U && sh ./check_format.sh`

Running well in my local now

**Review by lvjing2 — APPROVED** [review]
LGTM

**Pull request merged**
