### PR TITLE
remove invalid package #685

### PR DESCRIPTION
**Pull request by vchangpengfei**
remove invalid package

### CODE REVIEW

**Comment by vchangpengfei** [comment]
> 



> Hi @vchangpengfei, welcome to SOFAStack community, Please sign [Contributor License Agreement!](http://cla.sofastack.tech)
> 
> After you signed CLA, we will automatically sync the status of this pull request in 3 minutes.

done

**Comment by lvjing2** [comment]
please sign the CLA!

**Comment by vchangpengfei** [comment]
> 

done

**Review by lvjing2 — APPROVED** [review]
LGTM

**Pull request merged**
